<?php

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        'CL/remove_type_hint' => true,
        'return_type_declaration' => [
            'space_before' => 'none',
        ],
        'no_unused_imports' => true,
        'single_line_after_imports' => true,
        'class_attributes_separation' => [
            'elements' => [
                'const',
                'method',
                'property'
            ]
        ],
        'yoda_style' => false,
        'align_multiline_comment' => [
            'comment_type' => 'all_multiline',
        ],
        'self_accessor' => true,
        'array_syntax' => [
            'syntax' => 'short'
        ],
        'concat_space' => [
            'spacing' => 'one'
        ],
        'declare_strict_types' => false,
        'header_comment' => [
            'header' => <<<EOH
This file has been auto generated by Jane,

Do no edit it directly.
EOH
            ,
        ],
    ])
    ->registerCustomFixers([
        new \Tools\Fixer\RemoveTypeHintFixer()
    ]);
