<?php

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

return [
    'openapi-file' => __DIR__ . '/openapi.yaml',
    'namespace' => 'CloudLoyalty\Api\Generated',
    'directory' => __DIR__ . '/lib/Generated',
    'client' => 'psr18',
    'use-fixer' => true,
    'fixer-config-file' => '.php_cs.php',
];

