name: Lint PHP 5.4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@1.7.0
      with:
        php-version: '5.4'

    - run: php --version

    - name: Lint
      run: find lib/ -name \*.php -exec sh -c 'php -l "$0" || kill $PPID' \{\} \;
